global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "collector"
    static_configs:
      - targets: ["collector:9090"]
        labels:
          service: "collector"
          environment: "local"
